<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-MUIS24O" failures="3" tests="3" name="AuthTests" time="0.078" errors="0" timestamp="2020-09-15T17:46:34 CEST">
  <testcase classname="authenticationTests.AuthenticationForm" name="sucessAuthentication" time="0.006">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at authenticationTests.AuthenticationForm.sucessAuthentication(AuthenticationForm.java:17)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- sucessAuthentication -->
  <testcase classname="authenticationTests.AuthenticationForm" name="failedAuthentication" time="0.002">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at authenticationTests.AuthenticationForm.failedAuthentication(AuthenticationForm.java:33)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- failedAuthentication -->
  <testcase classname="authenticationTests.AuthenticationForm" name="incorrectPasswordAuth" time="0.002">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at authenticationTests.AuthenticationForm.incorrectPasswordAuth(AuthenticationForm.java:47)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- incorrectPasswordAuth -->
</testsuite> <!-- AuthTests -->
