<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2020-09-16T14:46:02 CEST" name="TheInternet" finished-at="2020-09-16T14:46:32 CEST" duration-ms="30279">
    <groups>
    </groups>
    <test started-at="2020-09-16T14:46:02 CEST" name="Test" finished-at="2020-09-16T14:46:32 CEST" duration-ms="30279">
      <class name="authenticationTests.AuthenticationForm">
        <test-method is-config="true" signature="browserSetUp()[pri:0, instance:authenticationTests.AuthenticationForm@49b0b76]" started-at="2020-09-16T14:46:02 CEST" name="browserSetUp" finished-at="2020-09-16T14:46:11 CEST" duration-ms="9305" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- browserSetUp -->
        <test-method signature="sucessAuthentication()[pri:1, instance:authenticationTests.AuthenticationForm@49b0b76]" started-at="2020-09-16T14:46:11 CEST" name="sucessAuthentication" finished-at="2020-09-16T14:46:12 CEST" duration-ms="1226" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The text does not match the expected secure message expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The text does not match the expected secure message expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:968)
at org.testng.Assert.assertTrue(Assert.java:43)
at authenticationTests.AuthenticationForm.sucessAuthentication(AuthenticationForm.java:25)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sucessAuthentication -->
        <test-method is-config="true" signature="recordFailure(org.testng.ITestResult)[pri:0, instance:authenticationTests.AuthenticationForm@49b0b76]" started-at="2020-09-16T14:46:12 CEST" name="recordFailure" finished-at="2020-09-16T14:46:13 CEST" duration-ms="329" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=sucessAuthentication status=FAILURE method=AuthenticationForm.sucessAuthentication()[pri:1, instance:authenticationTests.AuthenticationForm@49b0b76] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- recordFailure -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:authenticationTests.AuthenticationForm@49b0b76]" started-at="2020-09-16T14:46:13 CEST" name="tearDown" finished-at="2020-09-16T14:46:13 CEST" duration-ms="648" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="browserSetUp()[pri:0, instance:authenticationTests.AuthenticationForm@49b0b76]" started-at="2020-09-16T14:46:13 CEST" name="browserSetUp" finished-at="2020-09-16T14:46:21 CEST" duration-ms="7267" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- browserSetUp -->
        <test-method signature="failedAuthentication()[pri:2, instance:authenticationTests.AuthenticationForm@49b0b76]" started-at="2020-09-16T14:46:21 CEST" name="failedAuthentication" finished-at="2020-09-16T14:46:22 CEST" duration-ms="1230" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failedAuthentication -->
        <test-method is-config="true" signature="recordFailure(org.testng.ITestResult)[pri:0, instance:authenticationTests.AuthenticationForm@49b0b76]" started-at="2020-09-16T14:46:22 CEST" name="recordFailure" finished-at="2020-09-16T14:46:22 CEST" duration-ms="0" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=failedAuthentication status=SUCCESS method=AuthenticationForm.failedAuthentication()[pri:2, instance:authenticationTests.AuthenticationForm@49b0b76] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- recordFailure -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:authenticationTests.AuthenticationForm@49b0b76]" started-at="2020-09-16T14:46:22 CEST" name="tearDown" finished-at="2020-09-16T14:46:23 CEST" duration-ms="1266" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="browserSetUp()[pri:0, instance:authenticationTests.AuthenticationForm@49b0b76]" started-at="2020-09-16T14:46:23 CEST" name="browserSetUp" finished-at="2020-09-16T14:46:30 CEST" duration-ms="7092" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- browserSetUp -->
        <test-method signature="incorrectPasswordAuth()[pri:3, instance:authenticationTests.AuthenticationForm@49b0b76]" started-at="2020-09-16T14:46:30 CEST" name="incorrectPasswordAuth" finished-at="2020-09-16T14:46:31 CEST" duration-ms="1226" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- incorrectPasswordAuth -->
        <test-method is-config="true" signature="recordFailure(org.testng.ITestResult)[pri:0, instance:authenticationTests.AuthenticationForm@49b0b76]" started-at="2020-09-16T14:46:31 CEST" name="recordFailure" finished-at="2020-09-16T14:46:31 CEST" duration-ms="0" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=incorrectPasswordAuth status=SUCCESS method=AuthenticationForm.incorrectPasswordAuth()[pri:3, instance:authenticationTests.AuthenticationForm@49b0b76] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- recordFailure -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:authenticationTests.AuthenticationForm@49b0b76]" started-at="2020-09-16T14:46:31 CEST" name="tearDown" finished-at="2020-09-16T14:46:32 CEST" duration-ms="634" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- authenticationTests.AuthenticationForm -->
    </test> <!-- Test -->
  </suite> <!-- TheInternet -->
</testng-results>
